import ammo from "../assets/track/ammo.mp3";
import bark from "../assets/track/dog-bark-179915.mp3";
import sad from "../assets/track/mixkit-dog-whimper-sad-466.wav";
import waterA from "../assets/track/water-splash-199583.mp3";
import explosion from "../assets/track/explosion.mp3";
import fireSound from "../assets/track/fireplace-with-crackling-sounds-2-min-rk-178392-[AudioTrimmer.com].mp3";
import coronaSound from "../assets/track/monsterblizu.mp3";
import damage from "../assets/track/damage.mp3";
import flag from "../assets/track/flag.mp3";
import eating from "../assets/track/eating.mp3";
import run from "../assets/track/run.mp3";
import winGame from "../assets/track/mixkit-game-level-completed-2059.wav";
import loseGame from "../assets/track/mixkit-funny-fail-low-tone-2876.wav";
import bgm from "../assets/track/bgm.mp3";
import rocket from "../assets/track/rocket2.mp3";
export const winAudio = new Audio(winGame);
export const loseAudio = new Audio(loseGame);
export const eatingAudio = new Audio(eating);
export const flagAudio = new Audio(flag);
export const coronaAudio = new Audio(coronaSound);
export const fireAudio = new Audio(fireSound);
export const damageAudio = new Audio(damage);
export const waterAudio = new Audio(waterA);
export const explosionAudio = new Audio(explosion);
export const barkAudio = new Audio(bark);
export const sadAudio = new Audio(sad);
export const ammoAudio = new Audio(ammo);
export const runAudio = new Audio(run);
export const bgmAudio = new Audio(bgm);
export const rocketAudio = new Audio(rocket);
